language: java

notifications:
 email:
  recipients:
   marcosalles@gmail.com
  on_success: [always|never|change] # default: change
  on_failure: [always|never|change] # default: always
  template:
   - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
   - "Change view : %{compare_url}"
   - "Build details : %{build_url}"

before_install:
 - git clone git@github.com:marcosalles/cb-test.git sc
 - ./sc/before_install.sh

install:
 - ./sc/install.sh

before_script:
 - ./sc/before_script.sh

script:
 - ./sc/script.sh

after_script:
 - ./sc/after_script.sh